micronaut:
  application:
    name: spends
  server:
    port: 8080
spends:
  controller:
    path: "/spends"
users:
  controller:
    path: "/users"

datasources:
  default:
    url: jdbc:mysql://localhost:3306/spends
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    schema-generate: CREATE_DROP
    dialect: MYSQL

jpa:
  default:
    packages-to-scan:
      - "com.autentia.entities"
    reactive: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true